name: fav_books
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.4.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  riverpod_lint: ^2.3.7
  total_lints: ^3.2.0
flutter:
  uses-material-design: true
